import '../globals.css'; // Ajustez le chemin si nécessaire

import Loader from '@/components/Loader';
import { ClerkLoaded, ClerkLoading, ClerkProvider } from '@clerk/nextjs';
import { ReactNode } from 'react';

// Types pour les props de RootLayout
interface RootLayoutProps {
  children: ReactNode;
}

// Metadata pour le document
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

// Composant RootLayout en TypeScript
export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body>
          <ClerkLoading>
            <Loader />
          </ClerkLoading>
          <ClerkLoaded>
            {children}
          </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}
